// Auto-generated by extraction script
#pragma once
#include <Arduino.h>
extern const unsigned char bust[] PROGMEM;
extern const unsigned char win[] PROGMEM;
extern const unsigned char lost[] PROGMEM;
extern const unsigned char club[] PROGMEM;
extern const unsigned char heart[] PROGMEM;
extern const unsigned char spade[] PROGMEM;
extern const unsigned char diamond[] PROGMEM;
